pipeline:

  - set:
      value: "#{@list.create()}"
      output: "#{body}"

  - eval:
      expr: "#{body.add(@data.integerList(1,8))}"
  - eval:
      expr: "#{body.add(@data.integerList(9,16))}"
  - eval:
      expr: "#{body.add(@data.integerList(17,24))}"

  - script.run:
      script: |
        function command() {
          var res = [];
          pi.log.info(pi.message.body);
          for (index = 0; index < pi.message.body[0].length; ++index) {
            res.push([pi.message.body[0][index], pi.message.body[1][index], pi.message.body[2][index]]);
          }
          return JSON.stringify(res);
        }